[connections.mysql]
dialect = "mysql"
host = "localhost"
port = 3306
database = "--database name here--"
username = "root"
password = "saibabaSQL724"

[connections.mongodb]
url = "mongodb+srv://saiMongoDB:saibabaMDB724@cluster0.x3q0txw.mongodb.net/?retryWrites=true&w=majority"
database = "--database name here--"
collection = "--collection name here--"

